Make -s required.

diff --git a/abput b/abput
--- a/abput
+++ b/abput
@@ -20,7 +20,7 @@
 # MA 02111-1307, USA.
 
 prog="`basename \"$0\"`"
-rcs_revision='$Revision: 1.3 $'
+rcs_revision='$Revision: 1.4 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="abput (autobuild) $rcs_version
@@ -30,7 +30,7 @@ There is NO warranty.  You may redistribute this software under the
 terms of the GNU General Public License.  For more information about
 these matters, see the file named COPYING."
 
-usage="Usage: $prog [OPTION]... FILES...
+usage="Usage: $prog -s SYSTEM [OPTION]... FILES...
 
 Upload FILES to build platforms.
 
@@ -71,6 +71,12 @@ done
 if test $# -eq 0; then
     echo "$usage"
     exit 0
+fi
+
+if test -z "$SYSTEMS"; then
+    echo "$0: Missing --system parameter." >&2
+    echo "$0: Try \`--help' for more information." >&2
+    exit 1
 fi
 
 while test $# -gt 0; do
